[package]
name = "url_shorten"
version = "0.1.0"
edition = "2021"
publish = false

[profile.release]
debug = 1

[dependencies]
anyhow = "1.0.93"
bytes = "1.8.0"
fastly = "0.11.0"
rand = "0.8.5"
serde_json = "1.0.133"
chrono = "0.4.38"
