[package]
name = "url_shorten"
version = "0.1.1"
edition = "2021"
publish = false

[profile.release]
debug = 1

[dependencies]
anyhow = "1.0.95"
bytes = "1.10.0"
fastly = "0.11.2"
rand = "0.9.0"
serde_json = "1.0.138"
chrono = "0.4.39"
