[package]
name = "url_shorten"
version = "0.1.1"
edition = "2024"
publish = false

[profile.release]
debug = 1

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
fastly = "0.11.11"
rand = "0.9.2"
serde_json = "1.0.145"
chrono = "0.4.42"
